spring:
  datasource:
    url: jdbc:mysql://localhost:33060/jpashop
    username: root
    #url: jdbc:h2:tcp://localhost/~/jpashop
    #username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create #어플리케이션 실행 시 테이블 삭제 후 자동생성
    properties:
      hibernate:
        show_sql: true  #System.out으로 출력
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

logging:
  level:
    org.hibernate.sql: debug #JPA, Hibernate가 생성하는 SQL 확인, 로그로 출력
    org.hibernate.type: trace #SQL 파라미터 로깅


